# ========== Server ==========
server:
  port: 8080

# ========== MySQL, Redis ==========
spring:
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: "jdbc:mysql://localhost/writon"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


# ========== JWT ==========
jwt:
  secret: ${JWT_SECRET_KEY}


# ========== AWS S3 ==========
cloud:
  aws:
    s3:
      bucket: hoon-test-bucket
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false